eStoreClient/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Entities;
using System.Runtime.CompilerServices;
using eStoreClient.Models;
using StoreClient.Utils;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace eStoreClient.Controllers
{
    public class CategoryController : Controller
    {
        private readonly FstoreDbContext _context;
        private readonly ApiUrl _url;
        public CategoryController(FstoreDbContext context, ApiUrl url)
        {
            _context = context;
            _url = url;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            try
            {
                HttpResponseMessage response = await eStoreClientUtils.ApiRequest(
                    eStoreHttpMethod.GET,
                    _url.Default + "/Category");

                if (response.IsSuccessStatusCode)
                {
                    IEnumerable<Category> categories =
                        await response.Content.ReadAsAsync<IEnumerable<Category>>();
                    return View(categories);
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    return RedirectToAction("AccessDenied", "Login");
                }
                else
                {
                    throw new Exception(await response.Content.ReadAsStringAsync());
                }
            }
            catch (Exception ex)
            {
                ViewData["Categories"] = ex.Message;
                return View();
            }
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        [Authorize(Roles = "ADMIN")]
        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryName")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Delete/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        [Authorize(Roles = "ADMIN")]
        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'FstoreDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

eStoreClient/Controllers/LogoutController.cs
using eStoreClient.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoreClient.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eStoreClient.Controllers
{
    public class LogoutController : Controller
    {
        private readonly ApiUrl _api;

        public LogoutController(ApiUrl api)
        {
            _api = api;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            await eStoreClientUtils.ApiRequest(
                eStoreHttpMethod.POST,
                _api.Default + "/Member/logout");
            await HttpContext.SignOutAsync();
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Login");
        }
    }
}

eStoreClient/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BusinessObject.Entities;
using StoreClient.Utils;
using System.Security.Claims;
using eStoreClient.Models;
using Repository.Commons;
using Service.Model.Order;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Service.Model.SaleReportModel;
using System.IO.Pipelines;
using Azure;
using Microsoft.Extensions.Options;
using Repository.Repositories;
using Newtonsoft.Json;

namespace eStoreClient.Controllers
{
    public class OrderController : Controller
    {
        private readonly FstoreDbContext _context;
        private readonly ApiUrl _url;
        public OrderController(FstoreDbContext context, ApiUrl url)
        {
            _context = context;
            _url = url;
        }

        // GET: Order
        [Authorize]
        public async Task<IActionResult> Index()
        {
            try
            {
                HttpResponseMessage response;
                string fetchUrl = _url.Default + $"/Order/AllOrder?";

                if (!eStoreClientUtils.IsAdmin(User))
                {
                    string memberId = User.Claims.FirstOrDefault(claim => claim.Type.Equals(ClaimTypes.NameIdentifier)).Value;
                    fetchUrl += "/Order/memberId" + memberId;
                }
                response = await eStoreClientUtils.ApiRequest(
                    eStoreHttpMethod.GET,
                    fetchUrl);
                if (response.IsSuccessStatusCode)
                {
                    Pagination<OrderViewModel> orders =
                        await response.Content.ReadAsAsync<Pagination<OrderViewModel>>();
                    return View(orders);
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    return RedirectToAction("AccessDenied", "Login");
                }
                else
                {
                    throw new Exception(await response.Content.ReadAsStringAsync());
                }
            }
            catch (Exception ex)
            {
                ViewData["Orders"] = ex.Message;
                return View();
            }
        }

        // GET: Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }
            HttpResponseMessage response = await eStoreClientUtils.ApiRequest(
                    eStoreHttpMethod.GET,
                    _url.Default + "/Order/orderId/" + id);
            if (response.IsSuccessStatusCode)
            {
                Order order = await response.Content.ReadAsAsync<Order>();
                return View(order);
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                return RedirectToAction("AccessDenied", "Login");
            }
            else
            {
                throw new Exception(await response.Content.ReadAsStringAsync());
            }
        }

        private async Task<IEnumerable<Member>> GetMembersAsync()
        {
            HttpResponseMessage response = await eStoreClientUtils.ApiRequest(
                eStoreHttpMethod.GET,
                _url.Default + "/Member/AllMember");

            if (response.IsSuccessStatusCode)
            {
                IEnumerable<Member> members =
                    await response.Content.ReadAsAsync<IEnumerable<Member>>();
                return members;
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                throw new Exception("Failed to get members! Please log out and log in again...");
            }
            else
            {
                throw new Exception(await response.Content.ReadAsStringAsync());
            }
        }
        private async Task<IEnumerable<Product>> GetProductsAsync()
        {
            HttpResponseMessage response = await eStoreClientUtils.ApiRequest(
                eStoreHttpMethod.GET,
                _url.Default + "/Product");

            if (response.IsSuccessStatusCode)
            {
                IEnumerable<Product> products =
                    await response.Content.ReadAsAsync<IEnumerable<Product>>();
                return products;
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                throw new Exception("Failed to get products! Please log out and log in again...");
            }
            else
            {
                throw new Exception(await response.Content.ReadAsStringAsync());
            }
        }

        // GET: Order/Create
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Create()
        {
            try
            {
                ViewData["ProductsSelectedList"] = new SelectList(await GetProductsAsync(), "ProductId", "ProductName");
                IEnumerable<Member> members =
                    await GetMembersAsync();
                ViewData["MemberId"] = new SelectList(members, "MemberId", "Email");
                ViewData["OrderDetails"] = HttpContext.Session.GetData<List<OrderDetail>>("OrderCart");
                return View();
            }
            catch (Exception ex)
            {
                ViewData["Orders"] = ex.Message;
                return View();
            }
        }

        // POST: Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,MemberId,OrderDate,RequiredDate,ShippedDate,Freight")] Order order)
        {
            try
            {

                IEnumerable<Member> members =
                    await GetMembersAsync();
                ViewData["MemberId"] = new SelectList(members, "MemberId", "Email", order.MemberId);
                ViewData["ProductsSelectedList"] = new SelectList(await GetProductsAsync(), "ProductId", "ProductName");
                ViewData["OrderDetails"] = HttpContext.Session.GetData<List<OrderDetail>>("OrderCart");

                IEnumerable<OrderDetail> orderDetails = HttpContext.Session.GetData<List<OrderDetail>>("OrderCart");
                if (orderDetails == null || !orderDetails.Any())
                {
                    throw new Exception("Please add at least one item to your order details to create order");
                }
                order.OrderDetails = orderDetails.ToList();
                foreach (var od in order.OrderDetails)
                {
                    od.Product = null;
                }
                HttpResponseMessage response = await eStoreClientUtils.ApiRequest(
                eStoreHttpMethod.POST,
                _url.Default + "/Order", order);

                if (response.IsSuccessStatusCode)
                {
                    Order createdOrder = await response.Content.ReadAsAsync<Order>();
                    if (createdOrder == null)
                    {
                        throw new Exception("Failed to create order!! Please check again...");
                    }
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    return RedirectToAction("AccessDenied", "Login");
                }
                else
                {
                    throw new Exception("Validation error! Please check your input!");
                }
            }
            catch (Exception ex)
            {
                ViewData["Orders"] = ex.Message;
                return View();
            }
            HttpContext.Session.SetData("OrderCart", null);
            return RedirectToAction(nameof(Index));

        }
        private async Task<Product> GetProduct(int productId)
        {
            HttpResponseMessage response = await eStoreClientUtils.ApiRequest(
                    eStoreHttpMethod.GET,
                    _url.Default + "/Product/ProductId/" + productId);

            if (response.IsSuccessStatusCode)
            {
                Product product = await response.Content.ReadAsAsync<Product>();
                return product;
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
            {
                throw new Exception("Failed to get products! Please log out and log in again...");
            }
            else
            {
                throw new Exception(await response.Content.ReadAsStringAsync());
            }
        }
        private bool IsExistedInCart(IEnumerable<OrderDetail> cart, int productId)
        {
            return cart.Any(item => item.ProductId.Equals(productId));
        }
        [HttpPost]
        public async Task<IActionResult> AddToCart([Bind("ProductId", "Quantity", "Discount")] OrderDetailsModel orderDetails)
        {
            try
            {

                Product product = await GetProduct(orderDetails.ProductId);
                if (orderDetails.Quantity > product.UnitsInStock)
                {
                    throw new Exception("Quantity must be less than " + product.UnitsInStock);
                }
                List<OrderDetail> cart = HttpContext.Session.GetData<List<OrderDetail>>("OrderCart");
                if (cart == null)
                {
                    cart = new List<OrderDetail>();
                    cart.Add(new OrderDetail
                    {

eStoreClient/Views/Shared/_Layout.cshtml
@using StoreClient.Utils;
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/home.css" rel="stylesheet" />
    <!-- gLightbox gallery-->
    <link rel="stylesheet" href="~/vendor/glightbox/css/glightbox.min.css">
    <!-- Range slider-->
    <link rel="stylesheet" href="~/vendor/nouislider/nouislider.min.css">
    <!-- Choices CSS-->
    <link rel="stylesheet" href="~/vendor/choices.js/public/assets/styles/choices.min.css">
    <!-- Swiper slider-->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/vendor/swiper/swiper-bundle.min.css">
    <!-- Google fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@300;400;700&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Martel+Sans:wght@300;400;800&amp;display=swap">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="~/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="~/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/img/favicon.png">
    <link rel="stylesheet" href="~/NguyenManhToan_SE1604_A02.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="navbar">
            <div class="inner-width" style="background-color:#AD967C">
                @if (eStoreClientUtils.IsAdmin(User))
                {
                    <a asp-controller="Home" asp-action="Index" class="logo">FStore Shopping</a>
                    <a>
                        Welcome, Admin
                    </a>
                    <div class="navbar-menu">
                        <a class="nav-link" asp-controller="Order" asp-action="Index">Order</a>
                        <a class="nav-link" asp-controller="Members" asp-action="Index">Member</a>
                        <a class="nav-link" asp-controller="Category" asp-action="Index">Category</a>
                        <a class="nav-link" asp-controller="Product" asp-action="Index">Product</a>
                        <a class="nav-link" asp-controller="Logout" asp-action="Index">Logout</a>
                    </div>
                }
                else
                {
                    <a asp-controller="Home" asp-action="Index" class="logo">FStore Shopping</a>
                    <div class="navbar-menu">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">home</a>
                        <a asp-controller="Product" asp-action="Index" class="nav-link">Product</a>
                        <a asp-controller="Order" asp-action="Index" class="nav-link">Order</a>
                        <a asp-controller="Category" asp-action="Index" class="nav-link">Category</a>
                        <a class="nav-link" asp-controller="Login" asp-action="Index"> <i class="fas fa-dolly-flatbed me-1 text-gray"></i>Cart</a>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link" asp-controller="Login" asp-action="Index"> <i class="fas fa-user me-1 text-gray fw-normal"></i>Login</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Members" asp-action="Index">My Profile</a>
                            <a class="nav-link" asp-controller="Order" asp-action="Index">My Order</a>
                            <a class="nav-link" asp-controller="Logout" asp-action="Index">Logout</a>
                        }
                    </div>
                }
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="vendor/glightbox/js/glightbox.min.js"></script>
    <script src="vendor/nouislider/nouislider.min.js"></script>
    <script src="vendor/swiper/swiper-bundle.min.js"></script>
    <script src="vendor/choices.js/public/assets/scripts/choices.min.js"></script>
    <script src="js/front.js"></script>
    <script>
        // ------------------------------------------------------- //
        //   Inject SVG Sprite -
        //   see more here
        //   https://css-tricks.com/ajaxing-svg-sprite/
        // ------------------------------------------------------ //
        function injectSvgSprite(path) {

            var ajax = new XMLHttpRequest();
            ajax.open("GET", path, true);
            ajax.send();
            ajax.onload = function (e) {
                var div = document.createElement("div");
                div.className = 'd-none';
                div.innerHTML = ajax.responseText;
                document.body.insertBefore(div, document.body.childNodes[0]);
            }
        }
        // this is set to BootstrapTemple website as you cannot
        // inject local SVG sprite (using only 'icons/orion-svg-sprite.svg' path)
        // while using file:// protocol
        // pls don't forget to change to your domain :)
        injectSvgSprite('https://bootstraptemple.com/files/icons/orion-svg-sprite.svg');

    </script>
    <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="~/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/microsoft/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @*    <script src="~/js/site.js" asp-append-version="true"></script>
    *@    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>